services:
        base:
                image: julea-base-config
                build: 
                        context: .
                        dockerfile: docker/Dockerfile_base
                        args: 
                          build_path: "/etc/julea"
                          dependency_mode: "standard"
        server:
                build:
                        context: ./docker/server
                        dockerfile: Dockerfile_server
                depends_on:
                        - base
                image: julea-server-image
                ports: 
                        - "9876:9876"
                hostname: julea-server
                container_name: julea-server
        client:
                build:
                        context: ./docker/client
                        dockerfile: Dockerfile_client
                        args:
                          arg_build_path: "/etc/julea"
                depends_on:
                        - base
                image: julea-client-image
                hostname: julea-client
                container_name: julea-client
        compiler:
                build:
                        context: ./docker/build
                        dockerfile: Dockerfile_compiler
                        args:
                          arg_build_path: "/etc/julea"
                depends_on:
                        - base
                volumes:
                              - "./docker/build/files:/build"
                image: julea-client-compiler
                hostname: julea-client-compiler
                container_name: julea-client-compiler
