services:
        server:
                build:
                        context: ./docker/server
                        dockerfile: Dockerfile
                image: julea-server-image
                ports: 
                        - "9876:9876"
                hostname: julea-server
                container_name: julea-server
        client:
                build:
                        context: ./docker/client
                        dockerfile: Dockerfile
                image: julea-client-image
                hostname: julea-client
                container_name: julea-client
        volume:
                build:
                        context: ./docker/client
                        dockerfile: Dockerfile
                volumes:
                              - "./docker/build:/build"
                image: julea-client-image-volume
                hostname: julea-client-volume
                container_name: julea-client-volume
