FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get -y install --no-install-recommends \
	build-essential \
	curl \
	unzip \
	git \
	python3 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /julea-deps

COPY scripts/ .

SHELL ["/bin/bash", "-c"]

RUN ./install-dependencies.sh
