FROM ghcr.io/vittel1/julea-centos-deps-standard:1.0.0

WORKDIR /julea
COPY . .

SHELL ["/bin/bash", "-c"]
RUN . scripts/environment.sh && \
	meson setup --prefix="${HOME}/julea-install" bld && \
	ninja -C bld
