FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get -y install --no-install-recommends \
	build-essential \
	curl \
	unzip \
	python3

RUN apt-get -y install git

WORKDIR /julea
COPY scripts/ ./scripts/ 

SHELL ["/bin/bash", "-c"]
RUN ./scripts/install-dependencies.sh
