FROM ubuntu:20.04

#Path where JULEA is build in the container. Default is /etc/julea
ARG build_path=/etc/julea
#Install dependencies with options: minimal|standard|full. Default ist standard.
ARG dependency_mode=standard 

RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        unzip \
        git \
        python3

RUN echo "Install path: $build_path"
RUN echo "Dependency mode: $dependency_mode"

WORKDIR $build_path
COPY . .

SHELL ["/bin/bash", "-c"]

RUN ./scripts/install-dependencies.sh $dependency_mode

RUN . scripts/environment.sh && \
        meson setup --prefix="${HOME}/julea-install" -Db_sanitize=address,undefined bld && \
        ninja -C bld
